services: 
  mongo: 
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/textract
      PORT: 5000
    depends_on:
      - mongo
    networks:
      - backend-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo_data:
